{{- if .Values.operator.apiserver.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "llmos-operator.serviceAccountName" . }}
  labels:
    {{- include "llmos-operator.labels" . | nindent 4 }}
  {{- with .Values.operator.apiserver.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.operator.apiserver.serviceAccount.automount }}
{{- end }}
