# permissions for end users to edit upgrades.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: upgrade-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: llmos-controller
    app.kubernetes.io/part-of: llmos-controller
    app.kubernetes.io/managed-by: kustomize
  name: upgrade-editor-role
rules:
- apiGroups:
  - management.llmos.ai
  resources:
  - upgrades
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - management.llmos.ai
  resources:
  - upgrades/status
  verbs:
  - get
